# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95c70cea1250b4be315b440ab4beab76d624f1efcba85b72f5a5e2c619dd97850fcae453cf685935ba22986d2856cad7b09b417086e30c1dfebdb2eb2836d09c

test:
  secret_key_base: 46cf3f927654a9633be55cdf4d2eada99fc39d9c46e633ab67b356f231cae3a270598eaca28664a0a220ef3eb699875274b526d87a71dd5b62de26f98a5f3ad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
